"""Conversation state for follow-up turns.

Vercel functions are stateless, so multi-turn conversation needs somewhere to
put the state between requests. The session id is generated by the *browser*,
which keeps POST /api/execute a pure {"prompt": "..."} contract: a grader that
sends no session id simply gets a fresh one-shot run.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any, Protocol

from .config import SESSION_DIR, Settings
from .httpjson import HttpError, get_json, post_json
from .util import slugify

MAX_SESSION_BYTES = 256_000


class SessionStore(Protocol):
    name: str

    def get(self, session_id: str) -> dict[str, Any] | None: ...

    def put(self, session_id: str, state: dict[str, Any]) -> None: ...


def _session_dir() -> Path:
    """Prefer the repo's data dir locally; fall back to tmp on read-only hosts."""
    try:
        SESSION_DIR.mkdir(parents=True, exist_ok=True)
        probe = SESSION_DIR / ".writable"
        probe.write_text("ok", encoding="utf-8")
        probe.unlink()
        return SESSION_DIR
    except OSError:
        path = Path(tempfile.gettempdir()) / "atex-sessions"
        path.mkdir(parents=True, exist_ok=True)
        return path


class LocalSessionStore:
    name = "local"

    def _path(self, session_id: str) -> Path:
        return _session_dir() / f"{slugify(session_id)[:64] or 'session'}.json"

    def get(self, session_id: str) -> dict[str, Any] | None:
        path = self._path(session_id)
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None

    def put(self, session_id: str, state: dict[str, Any]) -> None:
        blob = json.dumps(state, ensure_ascii=False)
        if len(blob) > MAX_SESSION_BYTES:
            return
        try:
            self._path(session_id).write_text(blob, encoding="utf-8")
        except OSError:
            # A lost session degrades the next turn to a fresh run; it is never
            # worth failing the request the user actually asked for.
            pass


class SupabaseSessionStore:
    name = "supabase"

    def __init__(self, settings: Settings):
        self._settings = settings
        self._headers = {
            "apikey": settings.supabase_service_key,
            "Authorization": f"Bearer {settings.supabase_service_key}",
        }

    def get(self, session_id: str) -> dict[str, Any] | None:
        url = (
            f"{self._settings.supabase_url}/rest/v1/sessions"
            f"?select=state&session_id=eq.{session_id}&limit=1"
        )
        try:
            rows = get_json(url, headers=self._headers, timeout=10.0)
        except (HttpError, OSError):
            return None
        if isinstance(rows, list) and rows:
            state = rows[0].get("state")
            return state if isinstance(state, dict) else None
        return None

    def put(self, session_id: str, state: dict[str, Any]) -> None:
        url = f"{self._settings.supabase_url}/rest/v1/sessions?on_conflict=session_id"
        try:
            post_json(
                url,
                {"session_id": session_id, "state": state},
                headers={
                    **self._headers,
                    "Prefer": "resolution=merge-duplicates,return=minimal",
                },
                timeout=10.0,
                max_retries=0,
            )
        except (HttpError, OSError):
            pass


def build_session_store(settings: Settings) -> SessionStore:
    if settings.repository_backend == "supabase":
        return SupabaseSessionStore(settings)
    return LocalSessionStore()


def sanitize_session_id(raw: Any) -> str | None:
    """Accept only opaque, bounded identifiers; they become filenames."""
    if not isinstance(raw, str):
        return None
    cleaned = "".join(c for c in raw.strip() if c.isalnum() or c in "-_")[:64]
    return cleaned or None
