-- ATEX Supabase schema.
-- Run this in the Supabase SQL editor, then load data/seed/*.json with
-- scripts/push_supabase.py.

create table if not exists places (
    id                    text primary key,
    city                  text not null,
    country               text default '',
    name                  text not null,
    kind                  text not null check (kind in ('activity', 'hotel', 'restaurant')),
    area                  text default '',
    lat                   double precision default 0,
    lon                   double precision default 0,
    categories            jsonb  default '[]'::jsonb,
    typical_duration_min  integer default 90,
    price_level           text default 'mid',
    crowd_level           text default 'unknown',
    noise_level           text default 'unknown',

    -- Per-need claims: yes | limited | no | unknown. 'unknown' is a real,
    -- meaningful value here and must never be coerced to false.
    accessibility_claims  jsonb  default '{}'::jsonb,
    accessibility_source  text default 'unknown',
    source_url            text default '',
    last_verified         timestamptz,
    notes                 text default '',

    created_at            timestamptz default now()
);

create index if not exists places_city_kind_idx on places (lower(city), kind);
create index if not exists places_categories_idx on places using gin (categories);

-- Conversation state for follow-up turns. The session id is generated by the
-- browser, so /api/execute stays a pure {"prompt": "..."} contract for graders.
create table if not exists sessions (
    session_id   text primary key,
    state        jsonb not null default '{}'::jsonb,
    turn_count   integer not null default 0,
    updated_at   timestamptz not null default now()
);

create index if not exists sessions_updated_idx on sessions (updated_at desc);

-- Optional: cost observability across the $13 budget.
create table if not exists run_metrics (
    id                 bigserial primary key,
    session_id         text,
    prompt             text,
    llm_calls          integer,
    supervisor_turns   integer,
    total_tokens       integer,
    elapsed_seconds    double precision,
    stop_reason        text,
    created_at         timestamptz default now()
);

alter table places      enable row level security;
alter table sessions    enable row level security;
alter table run_metrics enable row level security;

-- The API uses the service key and bypasses RLS; no anon policies are granted
-- on purpose, so the tables are not publicly readable.
